/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   test/basic-test.html
 */

/// <reference path="../../webcomponentsjs/webcomponents-lite.d.ts" />
/// <reference path="../../web-component-tester/browser.d.ts" />
/// <reference path="../../fetch-polyfill/fetch-polyfill.d.ts" />
/// <reference path="test-element.d.ts" />

