/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   test/test-element.html
 */

/// <reference path="../../polymer/types/polymer-element.d.ts" />
/// <reference path="../headers-parser-behavior.d.ts" />

declare class TestElement extends Polymer.Element {
}

interface HTMLElementTagNameMap {
  "test-element": TestElement;
}
