language: node_js
node_js: 8
sudo: required
before_script:
- npm install -g polymer-cli
- polymer install --variants
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  sauce_connect: true
script:
- xvfb-run polymer test polymer test --plugin local
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test --plugin sauce --job-name
  "headers-parser-behavior:${TRAVIS_BRANCH}" --build-number=${TRAVIS_BUILD_NUMBER}; fi
cache:
  directories:
  - node_modules
after_success:
- node tasks/ci.js
env:
  global:
  - secure: pTSv3WnKygbv6EUopVEsoYGb8OrOIyA1IomhYXiewKTiB07tIiXknOpwpLePmnlIB0d1DRrnMR/fWEL+GV/ngIJFNgOd9Izh3Y1nWpyjhokfaxMJey/y2x1xetfEfXTJnvaJw1L6Tvp1j25jWMftkceOT+iqtM+6ZDchKRp8rRPRWR+6kW6x2HMVSHaTjgfDHU3LocXz184d0rpzO0qx3OwVFcZ00eLSVFzUkz+7JjUbQWm4Z6Dz4LIyKBVJ25F6STs11LzUQ7WqEqbaI6C2/486My6JbBb/4CuCHH9bHynlYuVhQDeUYcGDzATgCqKMCty15Scxqw5FO5vfmBZzdulwh3OsGYOe/24L/APoqYXYqED0Zkf9wyPF1cMzC8CSD7ose+pREKX/7y/UXwHecwK68/Ldd6nSZDIIh1j+EvNEuGyBEDatsFB2vIKtGtUBnifkzef+3YGr1oSLO+G+6FIRG9nsxldkr+zz8OMbfsVCTux/TO6v3Jl5h4x0cJNt0HMa3bg0wpGynwRiGTq1fhrkGWOU9szLm3mTVz19OI6U+7QTouL3oqD8wk/1W9TnFkJ5OOKgazWsr9N8P7rKR1UAP2H0QsFFZWsO2tPLZ1WY7KyQUTtnMaOKrs0/huArItJkngo/ddDdXcaahuIxnUilt0WjYYpj3B/5WsYfwFQ=
  - secure: JMujha1jD9p5XTdpnnn8ZDIOnNGHImvkFz+DfeGQkjbnO4jqKuoMekr7yVnsUKnAZLwub+uPQ0NUdh0MrGW3mhkDRPiHq5rU7NSY/TVxJ06KNLk1Oxmw8mZGaWnu9KOI9Fg3kcT+06fbGcbCU/Baj9JNRW/zljLmh6Hr+WTX3xc6osvlHhPY2wdx8amJc42VYKzno2mba0jpxscP+xD5J2dXTE/5fh46h0GOx8yXwLjpBuhbZyY1FrS+lc1E7A2GZkeEaF3u1QWoWrHFyEyRWz/IsxWbkV/GrfKs1JU5V8dtLnq82vZ/h6BN0iLoOvzmngXTVX+7avMnRU2klnr5JH8dyDi0dYYCVvw23KvWbA8MVGRfbxrBCTHs2vbgETnu61KE1lCJVaS9Gp0tj0is/fK6ZsXBl06er0Hm58z9QZ9r46qverlzrqs0zLB7FFwAgJjhFEuMNQOl22MlfdUAcruJlrdngMpwv7GKbuEiEzvGywGWwUUiPqPj3N2LW2FXhTAnitEAc1bHPKjF5w8+ieiJQBBQ1E0XtzSDXFSd4000j+tfDkEE92fG0q7xdBD9zCTyYAi2EixbD8RuFXuztkbYwH53L5aPleBZhAFyvB5GGQwEB1lOCukSDow+yXShUOw7kwEX6iUEEafO1Yi5GffHaQUZg/e8DHhbCk/jNJM=
